import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import { db } from "@/lib/firebase";

// Add Rozanova font
const rozanova = localFont({
  src: [
    {
      path: "../../public/fonts/RozanovaGEO-Demo-Thin.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/RozanovaGEO-Demo-SemiBold.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/RozanovaHUM-Demo-Thin.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/RozanovaHUM-Demo-Thin.otf",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (typeof window !== "undefined") {
  void db;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rozanova.className} antialiased`}>
        <Providers>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
